### ISSUE TITLE
Plugin removed issue

### ISSUE THREAD

**Issue by Micke1101** [Micke1101/OSTicket-plugin-field-radiobuttons#1]
If the plugin is removed and forms/help topics used the plugin, they will no longer be accessible.

**Comment by clonemeagain** [comment]
You can add a remove handler to the plugin, check for uses of the field and warn the admin via email of the error. Won't protect against deletion of the plugin folder.. but that will cause an error regardless of the plugin deleted if it's enabled.

eg: after the `bootstrap()` method

```php
    /**
     * Checks for uses of the field and warns the admin about the removal of the plugin.
     *
     * {@inheritdoc}
     *
     * @see Plugin::uninstall()
     */
    function uninstall() {
      $errors = array();

      // Check for usage
        $uses = DynamicFormField::objects()->filter(array('type' => 'radiobutton'))->all();
      if(count($uses)>0){
      global $ost;
      $ost->alertAdmin('Error! Plugin Radiobuttons Field has been uninstalled but is in use!',
        "This field type has been added to a Form, you will have errors!.",
        true);
      
      }

      parent::uninstall($errors);
    }```

**Comment by Micke1101** [comment]
I was thinking of either deleting all instances or replacing them with the choices field as that's what it resembles.
Going to look into the possibility to choose that on uninstall or maybe just have it as a setting.

**Comment by clonemeagain** [comment]
Ooh, changing them to choices would be a clever workaround, do that one!
